smsSurvery.Surveryer/Models/SurveyPlan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace smsSurvery.Surveryer.ClientModels
{
   public class ClientSurveyTemplate
   {
      public int Id { get; set; }
      public string Description { get; set; }
      public string Title { get; set; }
      public string ThankYouMessage { get; set; }
      public string IntroMessage { get; set; }
      public string DefaultLanguage { get; set; }
      public Nullable<DateTime> DateStarted { get; set; }
      public Nullable<DateTime> DateEnded { get; set; }
      public bool IsRunning { get; set; }
      public List<ClientQuestion> QuestionSet { get; set; }
      public string LogoLink { get; set; }
      public ClientTabletSettings TabletSettings { get; set; }
      public bool ShowCheckbox { get; set; }
      public string CheckboxText { get; set; }

      #region Calculated properties
      public string MobileWebsiteLocation { get; set; }      
      #endregion

      public ClientSurveyTemplate() { }

      public ClientSurveyTemplate(
         int iId,
         string iDescription,
         string iTitle,
         string iIntroMessage,
         string iThankYouMessage,         
         Nullable<DateTime> iDateStarted,
         Nullable<DateTime> iDateEnded,
         bool iIsRunning,
         List<ClientQuestion> iQuestionSet,
         String iDefaultLanguage,
         ClientTabletSettings iTabletSettings,
         bool iShowCheckbox,
         String iCheckboxText)
      {
         Id = iId;
         Description = iDescription;
         Title = iTitle;
         IntroMessage = iIntroMessage;
         ThankYouMessage = iThankYouMessage;
         DateStarted = iDateStarted;
         DateEnded = iDateEnded;
         IsRunning = iIsRunning;
         QuestionSet = iQuestionSet;
         DefaultLanguage = iDefaultLanguage;
         TabletSettings = iTabletSettings;
         ShowCheckbox = iShowCheckbox;
         CheckboxText = iCheckboxText;
      }     
   }
}

smsSurvery.Surveryer/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using smsSurvey.dbInterface;

namespace smsSurvery.Surveryer.Controllers
{
   [Authorize]
    public class QuestionController : Controller
    {
        private smsSurveyEntities db = new smsSurveyEntities();

        //
        // GET: /Question/

        public ActionResult Index()
        {
            return View(db.QuestionSet.OrderBy(q=> q.Order).ToList());
        }

        //
        // GET: /Question/Details/5

        public ActionResult Details(int id = 0)
        {
            Question question = db.QuestionSet.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
           if(question.Type == ReportsController.cFreeTextTypeQuestion)
           {
            //ViewBag.WordCloud = ReportsController.GetTagCloud(question);            
        }
            return View(question);
        }

        //
        // GET: /Question/Create

        public ActionResult Create(int surveyTemplateId)
        {
           //a question always belongs to a surveyTemplate
           var surveyTemplate = db.SurveyTemplateSet.Find(surveyTemplateId);
           if (surveyTemplate != null)
           {
              //by default the order should be max +1
              int maxOrder = 0;
              if (surveyTemplate.QuestionSet.Count > 0)
              {
               maxOrder =  surveyTemplate.QuestionSet.Max(q => q.Order);
              }
              Question newq = new Question()
              {
                 SurveyPlan_Id = surveyTemplateId,
                 Order = maxOrder + 1             
              };
              
              ViewBag.Action = "Create";
              return View(newq);
           }
           return null;
        }

        //
        // POST: /Question/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.QuestionSet.Add(question);
                db.SaveChanges();
                return RedirectToAction("Edit", "SurveyTemplate", new { id = question.SurveyPlan_Id });
            }

            return View(question);
        }

        //
        // GET: /Question/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Question question = db.QuestionSet.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Question/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                try
                {
                   db.SaveChanges();
                }
                catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
                {
                   foreach (var validationErrors in dbEx.EntityValidationErrors)
                   {
                      foreach (var validationError in validationErrors.ValidationErrors)
                      {
                         System.Diagnostics.Trace.TraceInformation("Property: {0} Error: {1}", validationError.PropertyName, validationError.ErrorMessage);
                      }
                   }
                }
                return RedirectToAction("Edit", "SurveyTemplate", new { id = question.SurveyPlan_Id });
            }
            return View(question);
        }

        //
        // GET: /Question/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Question question = db.QuestionSet.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Question/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.QuestionSet.Find(id);
            db.QuestionSet.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Edit", "SurveyTemplate", new { id = question.SurveyPlan_Id });
            //return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

smsSurvery.Surveryer/Controllers/ReportsController.cs
using smsSurvey.dbInterface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using smsSurvery.Surveryer.ReportHelpers;
using smsSurvery.Surveryer.WordCloud;
using System.Text;
using System.Text.RegularExpressions;
using System.Globalization;
using OfficeOpenXml;

namespace smsSurvery.Surveryer.Controllers
{
   [Authorize]
   public class ReportsController : Controller
   {
      public const string cRatingsTypeQuestion = "Rating";
      public const string cFreeTextTypeQuestion = "FreeText";
      public const string cYesNoTypeQuestion = "YesNo";
      public const string cSelectManyFromManyTypeQuestion = "SelectManyFromMany";
      public const string cSelectOneFromManyTypeQuestion = "SelectOneFromMany";
      public const string cNumericTypeQuestion = "Numeric";
      private const String cDateFormat = "yyyy-MM-dd H:mm:ss";

      private smsSurveyEntities db = new smsSurveyEntities();

      public const string STRING_COLUMN_TYPE = "string";
      public const string NUMBER_COLUMN_TYPE = "number";
      private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

      [HttpGet]
      public JsonResult GetSurveyResults(int surveyId)
      {
         string[] optionDef = new string[] { "Easy as pie", "Easy enough", "Average", "Rather hard", "Hard to use" };
         //for each question in the survey, aggregate the results
         SurveyTemplate survey = db.SurveyTemplateSet.Find(surveyId);
         //tags = tags ?? new string[0];
         QuestionSurveyResults res = null;
         if (survey != null)
         {
            foreach (var question in survey.QuestionSet)
            {
               switch (question.Type)
               {
                  case cRatingsTypeQuestion:
                     {
                        DateTime intervalStart = new DateTime(2013, 1, 1);
                        DateTime intervalEnd = new DateTime(2013, 12, 12);
                        res = GenerateResultForFiniteAnswersQuestion(question, intervalStart, intervalEnd, new string[0]);
                     }
                     break;
                  case cFreeTextTypeQuestion:

                     break;
                  default:
                     break;
               }
            }
         }
         if (res != null)
         {
            List<RepDataRow> pieChartContent = new List<RepDataRow>();
            foreach (var rowData in res.AnswersPerValidOption)
            {
               var row = new RepDataRow(new RepDataRowCell[] { new RepDataRowCell(rowData.Key, optionDef[Int32.Parse(rowData.Key) - 1]), new RepDataRowCell(rowData.Value, rowData.Value.ToString() + " answer(s)") });
               pieChartContent.Add(row);
            }

            RepChartData pieChartSource = new RepChartData(
               new RepDataColumn[] {
                new RepDataColumn("17", STRING_COLUMN_TYPE, "Type"),
                new RepDataColumn("18", STRING_COLUMN_TYPE, "Value") },
                  pieChartContent);
            //return Json(pieChartSource, JsonRequestBehavior.AllowGet);
            List<RepDataRow> tableData = new List<RepDataRow>()
            {
               new RepDataRow(new RepDataRowCell[] { new RepDataRowCell(res.TotalNumberOfAnswers, res.TotalNumberOfAnswers.ToString()), new RepDataRowCell(res.TotalNumberOfValidAnswers, res.TotalNumberOfValidAnswers.ToString()) })
            };
            RepChartData tableChartSource = new RepChartData(
               new RepDataColumn[] {
                new RepDataColumn("17", STRING_COLUMN_TYPE, "Total Answers"),
                new RepDataColumn("18", STRING_COLUMN_TYPE, "Valid Answers") },
                  tableData);
            var dataToSendBack = new { pie = pieChartSource, table = tableChartSource };
            return Json(dataToSendBack, JsonRequestBehavior.AllowGet);

         }
         return null;
      }

      [HttpGet]
      public JsonResult GetSurveyQuestionResults(int questionId, String iIntervalStart, String iIntervalEnd, string[] tags)
      {
         DateTime intervalStart = DateTime.ParseExact(iIntervalStart, cDateFormat, CultureInfo.InvariantCulture);
         DateTime intervalEnd = DateTime.ParseExact(iIntervalEnd, cDateFormat, CultureInfo.InvariantCulture);
         //for each question in the survey, aggregate the results
         Question question = db.QuestionSet.Find(questionId);
         QuestionSurveyResults res = null;
         //Return different data for various question types
         tags = tags ?? new string[0];
         List<Tags> processedTags = new List<Tags>();
         for (var i = 0; i < tags.Count(); ++i)
         {
            processedTags = processedTags.Union(processTag(tags[i])).ToList();
         }
         tags = processedTags.Select(x => x.Name).ToArray();
         switch (question.Type)
         {
            case cNumericTypeQuestion:
            case cRatingsTypeQuestion:
            case cYesNoTypeQuestion:
            case cSelectOneFromManyTypeQuestion:
               {
                  string[] optionDef = question.ValidAnswersDetails.Split(';');
                  res = GenerateResultForFiniteAnswersQuestion(question, intervalStart, intervalEnd, tags);
                  List<RepDataRow> pieChartContent = new List<RepDataRow>();
                  foreach (var rowData in res.AnswersPerValidOption)
                  {
                     //DA when dealing with Rating we expect that the valid answers array will be 1;2;3 - so to get the UserFriendlyName we -1
                     //for YesNo we have 0;1 - so we no longer need to subtract
                     var index = Int32.Parse(rowData.Key) - 1;
                     var row = new RepDataRow(new RepDataRowCell[] { new RepDataRowCell(rowData.Key, optionDef[index]), new RepDataRowCell(rowData.Value, rowData.Value.ToString() + " answer(s)") });
                     pieChartContent.Add(row);
                  }

                  RepChartData pieChartSource = new RepChartData(
                     new RepDataColumn[] {
                new RepDataColumn("17", STRING_COLUMN_TYPE, "Type"),
                new RepDataColumn("18", NUMBER_COLUMN_TYPE, "Value") },
                        pieChartContent);
                  List<RepDataRow> tableData = new List<RepDataRow>()
                        {
                           new RepDataRow(new RepDataRowCell[] { new RepDataRowCell(res.TotalNumberOfAnswers, res.TotalNumberOfAnswers.ToString()), new RepDataRowCell(res.TotalNumberOfValidAnswers, res.TotalNumberOfValidAnswers.ToString()) })
                        };
                  RepChartData tableChartSource = new RepChartData(
                     new RepDataColumn[] {
                new RepDataColumn("17", STRING_COLUMN_TYPE, "Total Answers"),
                new RepDataColumn("18", STRING_COLUMN_TYPE, "Valid Answers") },
                        tableData);
                  var dataToSendBack = new { pie = pieChartSource, table = tableChartSource };
                  return Json(dataToSendBack, JsonRequestBehavior.AllowGet);
               }
            case cFreeTextTypeQuestion:

               break;
            default:
               break;
         }
         return null;
      }


      private QuestionSurveyResults GenerateResultForFiniteAnswersQuestion(Question q, DateTime intervalStart, DateTime intervalEnd, string[] tags)
      {
         //we need the possible values - only valid answers are to be considered
         /**the output should contain
          * Total number of answers & total number of valid answers
          * For each valid value the number of answers
          */
         Dictionary<String, int> resultsPerAnswer = new Dictionary<String, int>();
         HashSet<string> validPossibleAnswers = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
         foreach (string validAnswerValue in q.ValidAnswers.Split(';'))
         {
            resultsPerAnswer.Add(validAnswerValue, 0);
            validPossibleAnswers.Add(validAnswerValue);
         }

         int validResponses = 0;
         var questionId = q.Id;
         tags = tags ?? new string[0];
         IEnumerable<Result> resultsToAnalyze = null;

         //DA - lazy DA inserted the check for length due to "The LINQ expression node type 'ArrayLength' is not supported in LINQ to Entities." instead of figuring out what the problem is
         if (tags.Length == 0)
         {
            resultsToAnalyze = from r in db.ResultSet
                               where r.QuestionId == questionId &&
                intervalEnd >= r.DateSubmitted &&
                intervalStart <= r.DateSubmitted
                               select r;
         }
         else
         {
            resultsToAnalyze = from r in db.ResultSet
                               where r.QuestionId == questionId &&
                               intervalEnd >= r.DateSubmitted &&
                               intervalStart <= r.DateSubmitted &&
                               tags.Intersect(r.SurveyResult.Tags.Select(tag => tag.Name)).Any()
                               select r;
         }

         foreach (var result in resultsToAnalyze)
         {
            if (q.Type.Equals(cSelectManyFromManyTypeQuestion))
            {
               var answers = result.Answer.Split(';');
               foreach (var answer in answers) {
                  var isContained = validPossibleAnswers.Contains(answer);
                  if (isContained)
                  {
                     resultsPerAnswer[answer] = resultsPerAnswer[answer] + 1;
                     validResponses++;
                  }
               }              
            }
            else
            {
               if (validPossibleAnswers.Contains(result.Answer))
               {
                  resultsPerAnswer[result.Answer] = resultsPerAnswer[result.Answer] + 1;

smsSurvery.Surveryer/Views/SurveyPlan/Create.cshtml
@{
    ViewBag.Title = "Create survey";
}
@{Html.RenderPartial("SurveyEditor");}

@section Scripts {
   @Scripts.Render("~/bundles/jqueryval")
   @Scripts.Render("~/bundles/myscripts")
}

@section css {
   @Styles.Render("~/bundles/SurveyPlan")
}

smsSurvery.Surveryer/Views/SurveyPlan/CreateEditSurveyPlan.cshtml
@model smsSurvey.dbInterface.SurveyPlan

<fieldset class="surveyPlan">
   <legend>SurveyPlan</legend>

    @if (Model != null)
    {
         @Html.HiddenFor(model => model.Id)
         @Html.HiddenFor(model => model.Provider)
    }
   <table class="txteditor table table-striped table-bordered table-hover">
      <tr>
         <td class="labelCol" >
            @Html.DisplayNameFor(model => model.Description)
         </td>
         <td>
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
         </td>
      </tr>
      <tr>
         <td class="labelCol">
            @Html.DisplayNameFor(model => model.ThankYouMessage)
         </td>
         <td>
            @Html.EditorFor(model => model.ThankYouMessage)
            @Html.ValidationMessageFor(model => model.ThankYouMessage)
         </td>
      </tr>
      <tr>
         <td class="labelCol">
            @Html.DisplayNameFor(model => model.DateStarted)
         </td>
         <td>
            @Html.HiddenFor(model => model.DateStarted)
            @Html.DisplayFor(model => model.DateStarted)
            @Html.ValidationMessageFor(model => model.DateStarted)
         </td>
      </tr>
      <tr>
         <td class="labelCol">
            @Html.DisplayNameFor(model => model.DateEnded)
         </td>
         <td>
            @Html.HiddenFor(model => model.DateEnded)
            @Html.DisplayFor(model => model.DateEnded)
            @Html.ValidationMessageFor(model => model.DateEnded)
         </td>
      </tr>
      <tr>
         <td class="labelCol">
            @Html.DisplayNameFor(model => model.IsRunning)
         </td>
         <td>
            @Html.CheckBoxFor(model => model.IsRunning,new { disabled = "disabled", @readonly = "readonly" })
         </td>
      </tr>
   </table>
   @if (ViewBag.Action == "Create")
   {
      <input class="btn btn-primary" type="submit" value="Create" />
      }
   else
   {
      <input class="btn btn-primary" type="submit" value="Save" />
   }    
</fieldset>

smsSurvery.Surveryer/Views/SurveyPlan/Delete.cshtml
@model smsSurvey.dbInterface.SurveyPlan

@{
    ViewBag.Title = "Delete survey";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>SurveyPlan</legend>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

smsSurvery.Surveryer/Views/SurveyPlan/Details.cshtml
@model smsSurvey.dbInterface.SurveyPlan

@{
    ViewBag.Title = "Survey details";
}

<h2>Details</h2>

<fieldset class="surveyPlan">
    <legend>SurveyPlan</legend>
    <table class="table table-striped table-bordered table-hover">
       <tr>
          <td class="labelCol">
               @Html.DisplayNameFor(model => model.Description)
          </td>
          <td>
              @Html.DisplayFor(model => model.Description)
          </td>
       </tr>
       <tr>
          <td class="labelCol">
               @Html.DisplayNameFor(model => model.ThankYouMessage)
          </td>
          <td>
              @Html.DisplayFor(model => model.ThankYouMessage)
          </td>
       </tr>
       <tr>
          <td class="labelCol">
               @Html.DisplayNameFor(model => model.DateStarted)
          </td>
          <td>
              @Html.DisplayFor(model => model.DateStarted)
          </td>
       </tr>
       <tr>
          <td class="labelCol">
               @Html.DisplayNameFor(model => model.DateEnded)
          </td>
          <td>
              @Html.DisplayFor(model => model.DateEnded)
          </td>
       </tr>
       <tr>
          <td class="labelCol">
               @Html.DisplayNameFor(model => model.IsRunning)
          </td>
          <td>
              @Html.DisplayFor(model => model.IsRunning)
          </td>
       </tr>
    </table>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>


<h2> Questions</h2>
@if (Model.QuestionSet.Count != 0)
{
<table class="table table-striped table-bordered table-hover"> @*class="questionsTable"*@
    <tr>
        <th>
           Text
        </th>
        <th>
            Order
        </th>
        <th>
            Type
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.QuestionSet) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Order)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", "Question", new RouteValueDictionary { {"id",item.Id} }, null) 
        </td>
    </tr>
}
</table>   
}
else {
   <p>
      No questions defined so far. How about adding a question to this survey?
      Edit the survey to continue.
   </p>
}

smsSurvery.Surveryer/Views/SurveyPlan/Edit.cshtml
@{
   ViewBag.Title = "Edit survey";
}
@{Html.RenderPartial("SurveyEditor");}

@section Scripts {
   @Scripts.Render("~/bundles/jqueryval")
   @Scripts.Render("~/bundles/myscripts")
}

@section css {
   @Styles.Render("~/bundles/SurveyPlan")
}

smsSurvery.Surveryer/Views/SurveyPlan/Index.cshtml
@model IEnumerable<smsSurvey.dbInterface.SurveyPlan>

@{
    ViewBag.Title = "Survey list";
}

@using MvcPaging;
@using smsSurvey.dbInterface;

@{
   IPagedList<SurveyPlan> pagingDetails = ViewBag.pagingDetails;
   RouteValueDictionary r = new RouteValueDictionary();
   r.Add("to", Request["to"]);
   r.Add("from", Request["from"]);
   r.Add("text", Request["text"]);
}

<h2>Survey templates</h2>

<p>
   @* Create new survey part *@
    <a href="/SurveyPlan/Create" class="btn btn-primary delete-btn">Create survey template</a>
</p>
@{Html.RenderPartial("SearchBoxItems", "SurveyPlan");}
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThankYouMessage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateStarted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateEnded)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsRunning)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThankYouMessage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateStarted)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateEnded)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsRunning)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
           @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |            
           @if(item.IsRunning) {
            @Html.ActionLink("Stop", "MakeActive", new { id=item.Id })           
           } else {
              @Html.ActionLink("Make active", "MakeActive", new { id=item.Id }) 
           } |
            @Html.ActionLink("Report", "Report","SurveyPlan", new { id=item.Id }, null) |
            @Html.ActionLink("Comparison report", "GetTagComparisonReport","Reports", new { surveyId=item.Id }, null) |
            @Html.ActionLink("Responses", "Responses","SurveyPlan", new { id=item.Id }, null)
        </td>
    </tr>
}

</table>
@Html.Pager(pagingDetails.PageSize, pagingDetails.PageNumber, pagingDetails.TotalItemCount, r)

@section css {
   @Styles.Render("~/bundles/SurveyResult")
}

smsSurvery.Surveryer/Views/SurveyPlan/Report.cshtml
@model smsSurvey.dbInterface.SurveyPlan

@{
    ViewBag.Title = "Survey report";
}

<script type="text/javascript" src='https://www.google.com/jsapi?autoload={"modules":[{"name":"visualization","version":"1","packages":["corechart","table"]}]}'></script>

<text>
@{Html.RenderPartial("SurveyResultOverview", (smsSurvey.dbInterface.SurveyPlan) Model);}
</text>

@if (Model != null)
{
   <text>
    @{Html.RenderPartial("SurveyReport", (IEnumerable<smsSurvey.dbInterface.Question>) Model.QuestionSet.OrderBy(q => q.Order));} 
   </text>
}
else
{
   <p>
      If you are reading this then you have stumbled into an "under construction" area - congrats!
   </p>      
}   
@section css{
   @Styles.Render("~/Content/custom")
}

@section Scripts {
@Scripts.Render("~/bundles/referencescripts")
@Scripts.Render("~/bundles/activityReports")
}