smsSurvery.Surveryer/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using smsSurvey.dbInterface;

namespace smsSurvery.Surveryer.Controllers
{
   [Authorize]
    public class CustomerController : Controller
    {
        private smsSurveyEntities db = new smsSurveyEntities();

        //
        // GET: /Customer/

        public ActionResult Index()
        {
            return View(db.CustomerSet.ToList());
        }

        //
        // GET: /Customer/Details/5

        public ActionResult Details(string id = null)
        {
            Customer customer = db.CustomerSet.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // GET: /Customer/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Customer/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.CustomerSet.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customer);
        }

        //
        // GET: /Customer/Edit/5

        public ActionResult Edit(string id = null)
        {
            Customer customer = db.CustomerSet.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // POST: /Customer/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        //
        // GET: /Customer/Delete/5

        public ActionResult Delete(string id = null)
        {
            Customer customer = db.CustomerSet.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // POST: /Customer/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Customer customer = db.CustomerSet.Find(id);
            db.CustomerSet.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

smsSurvery.Surveryer/Controllers/SurveyResultController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using smsSurvey.dbInterface;
using MvcPaging;
using System.Data.Entity.Validation;
using System.Text;

namespace smsSurvery.Surveryer.Controllers
{
   [Authorize]
    public class SurveyResultController : Controller
    {
        private smsSurveyEntities db = new smsSurveyEntities();
        private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        //
        // GET: /SurveyResult/

        [Authorize]
        public ActionResult Index(int page=1)
        {
           int currentPageIndex = page - 1;
           int NUMBER_OF_RESULTS_PER_PAGE = 10;
           var user = db.UserProfile.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
           var res = db.SurveyResultSet.Where(x => x.SurveyTemplate.UserProfile.FirstOrDefault().UserName == User.Identity.Name).OrderByDescending(x => x.DateRan);
           var pageRes = res.Skip((page - 1) * NUMBER_OF_RESULTS_PER_PAGE).Take(NUMBER_OF_RESULTS_PER_PAGE);
           IPagedList<SurveyResult> pagingDetails = new PagedList<SurveyResult>(res, currentPageIndex, NUMBER_OF_RESULTS_PER_PAGE, res.Count());
           ViewBag.pagingDetails = pagingDetails;
           return View(pageRes.ToList());
        }      

        //
        // GET: /SurveyResult/Details/5

        public ActionResult Details(int id = 0)
        {
            SurveyResult surveyresult = db.SurveyResultSet.Find(id);
            if (surveyresult == null)
            {
                return HttpNotFound();
            }
            foreach (var res in surveyresult.Result)
            {
               res.HumanFriendlyAnswer = AlertsController.GetUserFriendlyAnswerVersion(res.Question, res.Answer, logger);
            }
            return View(surveyresult);
        }

        //
        // GET: /SurveyResult/Create

        public ActionResult Create()
        {
            ViewBag.CustomerPhoneNumber = new SelectList(db.CustomerSet, "PhoneNumber", "Name");
            ViewBag.SurveyTemplateId = new SelectList(db.SurveyTemplateSet, "Id", "Description");
            return View();
        }

        //
        // POST: /SurveyResult/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SurveyResult surveyresult)
        {
            if (ModelState.IsValid)
            {
                db.SurveyResultSet.Add(surveyresult);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerPhoneNumber = new SelectList(db.CustomerSet, "PhoneNumber", "Name", surveyresult.CustomerPhoneNumber);
            ViewBag.SurveyTemplateId = new SelectList(db.SurveyTemplateSet, "Id", "Description", surveyresult.SurveyPlanId);
            return View(surveyresult);
        }

        //
        // GET: /SurveyResult/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SurveyResult surveyresult = db.SurveyResultSet.Find(id);
            if (surveyresult == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerPhoneNumber = new SelectList(db.CustomerSet, "PhoneNumber", "Name", surveyresult.CustomerPhoneNumber);
            ViewBag.SurveyTemplateId = new SelectList(db.SurveyTemplateSet, "Id", "Description", surveyresult.SurveyPlanId);
            return View(surveyresult);
        }

        //
        // POST: /SurveyResult/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SurveyResult surveyresult)
        {
            if (ModelState.IsValid)
            {
                db.Entry(surveyresult).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerPhoneNumber = new SelectList(db.CustomerSet, "PhoneNumber", "Name", surveyresult.CustomerPhoneNumber);
            ViewBag.SurveyTemplateId = new SelectList(db.SurveyTemplateSet, "Id", "Description", surveyresult.SurveyPlanId);
            return View(surveyresult);
        }

        //
        // GET: /SurveyResult/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SurveyResult surveyresult = db.SurveyResultSet.Find(id);
            if (surveyresult == null)
            {
                return HttpNotFound();
            }
            return View(surveyresult);
        }

        //
        // POST: /SurveyResult/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           try
           {
              SurveyResult surveyresult = db.SurveyResultSet.Find(id);
              var individualResults = surveyresult.Result.ToList();
              foreach (var item in individualResults)
              {

                 db.ResultSet.Remove(item);
              }
              //remove the associated tags                          
              var tags = surveyresult.Tags.ToList();
              foreach (var tag in tags)
              {
                 surveyresult.Tags.Remove(tag);
              }
              db.SurveyResultSet.Remove(surveyresult);

              db.SaveChanges();
              return RedirectToAction("Index");
           }

           catch (DbEntityValidationException ex)
           {
              StringBuilder sb = new StringBuilder();
              foreach (var failure in ex.EntityValidationErrors)
              {
                 sb.AppendFormat("{0} failed validation\n", failure.Entry.Entity.GetType());
                 foreach (var error in failure.ValidationErrors)
                 {
                    sb.AppendFormat("- {0} : {1}", error.PropertyName, error.ErrorMessage);
                    sb.AppendLine();
                 }
              }
              logger.Error(sb.ToString());
              //TODO DA - return error to user
              return RedirectToAction("Index");
           }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

smsSurvery.Surveryer/Views/Shared/MobileSurvey.cshtml
@using smsSurvery.Surveryer.GlobalResources

<script id="mobileSurveyTemplate" type="text/template">
   <div class="questionsArea">
   </div>
</script>
<script id="question-mobile-template" type="text/template">
   <div class="question">
      <h4 class="questionTitle"><%= QuestionNumber %>. <%= Text %> </h4>
      <div class="answerArea">
         <%
            if (Type == SurveyUtilities.Utilities.CONSTANTS_QUESTION.TYPE_YES_NO) { %>
                  <input type="radio" id="y-<%= QuestionNumber %>" name="yes-no-answer<%= Id %>" value="1">
         <label for="y-<%= QuestionNumber %>">@Global.MobileSurveyYesLabel</label>
         <input type="radio" id="n-<%= QuestionNumber %>" name="yes-no-answer<%= Id %>" value="2">
         <label for="n-<%= QuestionNumber %>">@Global.MobileSurveyNoLabel</label>
         <% 
            } else if (Type == SurveyUtilities.Utilities.CONSTANTS_QUESTION.TYPE_FREE_TEXT) {
         %>
                  <textarea class="answer comment"></textarea>
         <%
            } else if (Type == SurveyUtilities.Utilities.CONSTANTS_QUESTION.TYPE_RATING) {
         %>
         
         <%
         } else if (Type == SurveyUtilities.Utilities.CONSTANTS_QUESTION.TYPE_SELECT_MANY_FROM_MANY) { 
            _.each(Answers, function(answer, index) {  %>                     
               <input type="checkbox" id="m-a-<%= answer.AnswerIdentifier %>" class="css-checkbox" value="<%= answer.AnswerIdentifier %>" />
         <label for="m-a-<%= answer.AnswerIdentifier %>" name="multiple-answers-label" class="css-label"><%=answer.AnswerLabel %></label>
         <% });
         } else if (Type == SurveyUtilities.Utilities.CONSTANTS_QUESTION.TYPE_SELECT_ONE_FROM_MANY) {
         %>     
            <select class="answer list" name="answer">
               <option value="noValue">@Global.MobileSurveySelectOneFromManyLabel</option>
               <% _.each(Answers, function(value, key, list) { %>
                  <option value="<%= value.AnswerIdentifier %>"><%= value.AnswerLabel %></option>
               <% }); %> 
            </select>
         <%
         } else if (Type == SurveyUtilities.Utilities.CONSTANTS_QUESTION.TYPE_NUMERIC) {
            var numericValues = ValidAnswers.split(";");
            var numericLabels = ValidAnswersDetails.split(";");
            if (numericValues.length > 0) {
         %>
         <div class="scale-legend-wrapper">
            <div class="scale-legend">
               <div class="low-scale"><< <%= numericLabels[0] %></div>
               <div class="high-scale"><%= numericLabels[numericLabels.length - 1] %> >></div>
               <div class="clear"></div>
            </div>
         </div>
         <div class="scale-wrapper">
            <%
            for (var i=0; i < numericValues.length; ++i) {
         %>                        
            <div class="numeric-entry">
               <label for="radio<%= numericValues[i] %><%= Id %>" class="numeric-value-label">
                  <span class="numeric-value"><%= numericValues[i] %></span>
               </label>
               <input class="numeric-radio" id="radio<%= numericValues[i] %><%= Id %>" type="radio" value="<%= numericValues[i] %>" name="numeric-scale-answer<%= Id %>" />
            </div>
            <%
            } 
         }%>
            <div class="clear"></div>
         </div>
         <textarea class='comment invisibleByDefault' placeholder="@Global.MobileSurveyRatingAddionalInfoLabel"></textarea>
         <%   
     } 
      %>      
      </div>
   </div>
</script>

<script type="text/template" id="star-template">
   <% if (Active) { %>
            <a href="#" class="starImg starActive" src="/Content/images/stars.png" />
   <% } else { %>
            <a href="#" class="starImg" src="/Content/images/stars.png" />
   <% } %>
</script>

<script type="text/template" id="star-bar-template">
   <div class="starsArea">
   </div>
   <textarea class='comment invisibleByDefault' placeholder="@Global.MobileSurveyRatingAddionalInfoLabel"></textarea>
   <input type='hidden' class='answer' value='noValue' />
</script>

<script type="text/template" id="thankyoupage-template">
   <header>
      <div class="headerContainer">
         <img id="pageIcon" src="/Content/images/small-icon.png" />
         <h3 id="pageTitle">@ViewBag.SurveyTitle</h3>
      </div>
   </header>
   <section id="thankYouMessage" class="surveyMessage">
      <p id="surveySubmitted">@Global.MobileSurveySurveySent</p>
      <p id="thankYouMessageContent">
         @ViewBag.ThankYouMessage
      </p>
      <div style="display: none" class="alert fade in alert-error" id="noTags-error">
         <div class="personal-info-validation">
         </div>
      </div>
   </section>
   @if ((int)@ViewBag.IsFeedback != 0)
   {
      <div id="userInfo">
         <div id="surveyUserInfo">            
            <div class="personalInfoFields">
               <div>
                  <label for="name">@Global.MobileSurveyPersonalInfoNameLabel</label>
                  <input id="name" type="text" /><br />
               </div>
               <div>
                  <label for="surname">@Global.MobileSurveyPersonalInfoSurnameLabel</label>
                  <input id="surname" type="text" /><br />
               </div>
               <div>
                  <label for="email">@Global.MobileSurveyPersonalInfoEmailLabel</label>
                  <input id="email" type="email" /><br />
               </div>
               <div>
                  <label for="telephone">@Global.MobileSurveyPersonalInfoPhoneLabel</label>
                  <input id="telephone" type="tel" />
               </div>
            </div>         
         </div>
         <button id="sendPersonalDetailsBtn" class="enabled">@Global.MobileSurveyPersonalInfoSubmitBtnLabel</button>
         <input id="personalInfoSubmitted" type='hidden' value='@Global.MobileSurveyPersonalInfoSubmittedLabel' />
      </div>
   }
   @if (@ViewBag.TabletView)
   {
      <a class="retakeBtn" href="#" onclick="location.reload()">@Global.MobileSurveyPersonalInfoRetakeSurvey</a>
   }
</script>


<input type="hidden" value="@ViewBag.Id" id="surveyTemplateId"/>
<input type="hidden" value="@ViewBag.IsFeedback" id="isFeedback"/>
<section id="survey">
   <section id="questionsPage" class="page">
      <header>
         <div class="headerContainer">
            <img id="pageIcon" src="/Content/images/small-icon.png" />
            <h3 id="pageTitle">@ViewBag.SurveyTitle</h3>
         </div>
      </header>
      <div class="clear" />
      <section id="introMessage" class="surveyMessage">
         <p>
            @ViewBag.IntroMessage
         </p>
      </section>
      <section id="questions">
      </section>
      <div id="doneBtnWrapper">
         <button id="doneBtn"></button>
      </div>
      <footer>
         <span>@Global.MobileSurveyFooterCaption
            <a href="http://www.txtfeedback.net">TxtFeedback
            </a>
         </span>
      </footer>
      <input type="hidden" value="@Global.MobileSurveySubmitButtonCaption" id="doneBtnTitle" />
      <input type="hidden" value="@ViewBag.Location" id="location" />
   </section>
   <section id="thankYouPage" class="page" style="display: none">
   </section>
   <div class="clear" />
</section>
<input type="hidden" value="@Global.MobileSurveyPersonalInfoNameError" id="mobileSurveyPersonalInfoNameError" />
<input type="hidden" value="@Global.MobileSurveyPersonalInfoSurnameError" id="mobileSurveyPersonalInfoSurnameError" />
<input type="hidden" value="@Global.MobileSurveyPersonalInfoEmailError" id="mobileSurveyPersonalInfoEmailError" />

smsSurvery.Surveryer/Views/Shared/QuestionDetails.cshtml
@model smsSurvey.dbInterface.Question
@using smsSurvery.Surveryer.Extensions
@{
    ViewBag.Title = "Details";
}
<div class="questionArea">
<fieldset>
    <legend>Question @Model.Order</legend>
    <div class="display-field">
       @Html.DisplayFor(model => model.Text)
       @* we specify the question in case (will be needed later to get the report data) *@
       @Html.HiddenFor(model => model.Id, new { qid = Model.Id, qtype=Model.Type})
    </div>    
  
</fieldset>

 <div   id="@String.Format("graphsContainer{0}", Model.Id)" class="graphsContainer">   
   <div id="@String.Format("tableChart_div{0}", Model.Id)"></div>
   <div id="@String.Format("pieChart_div{0}", Model.Id)"></div>
   <div id="@String.Format("textCloudSection{0}", Model.Id)"></div>
   <div id="@String.Format("barChart_div{0}", Model.Id)" qid="@Model.Id" qtype="@Model.Type" class="chart"></div>         
   <div id="@String.Format("loadingIndicator{0}", Model.Id)" style="display:none" class="loadingIndicatorArea">
      <div class="loadingIndicatorContainer">
         <img src="~/Content/images/ajax-loader_vs1.gif" class="loadingIndicatorIcon" />
      </div>
      <div class="overlay"></div>
   </div>
  
</div>
 @if (Model.Type == smsSurvery.Surveryer.Controllers.ReportsController.cRatingsTypeQuestion
    || Model.Type == smsSurvery.Surveryer.Controllers.ReportsController.cNumericTypeQuestion)
   {
    <div class="additionalInfoContainer">
      <label class="additionalInfoLabel">Provided qualifications</label>
      <div id="@String.Format("textCloudSectionAdditionalInfo{0}", Model.Id)"></div>      
    </div>
   }
</div>

smsSurvery.Surveryer/Views/Shared/ReportFilterArea.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<div id="tagContainer" >
      <div id="wrapperForTags" rel="popover" data-content="Using this filter, select the locations for which you would like to visualize the report for and hit Generate report" data-original-title="Select location">
       <input name="filterTag" id="filterTag" type="text"  />
      </div>
   <div class="secondRow">
      <div class="dateSelectorArea">
          <label class="dateFilterHorizontalLabel">Start Date </label><input type="text" id="from" name="from" class="filterDate filterInputBox"  value=""/>
         <label class="dateFilterHorizontalLabel">End Date </label><input type="text" id="to" name="to" class="filterDate filterInputBox"  value=""/>
      </div>
      <button id="refreshReport" class="btn btn-primary" value="Generate report" >Generate report</button>
   </div>
 </div>

smsSurvery.Surveryer/Views/Shared/SearchBoxItems.cshtml
@model string
@using (Html.BeginForm("Search", Model, null, FormMethod.Get))
{
   <div class="searchBox noprint">      
      <input class="description-filter-input" name="text" id="text" type="text" value="@Request["text"]"
              placeholder="Description to look for..." />
       <input type="submit" value="Filter surveys" class="btn btn-primary filter-submit-btn" />
   </div>
}

smsSurvery.Surveryer/Views/Shared/SurveyReport.cshtml
@model IEnumerable<smsSurvey.dbInterface.Question>

<h3>Results per question</h3>
@foreach (var q in Model)
{
   Html.RenderPartial("QuestionDetails", (smsSurvey.dbInterface.Question) q);
}

smsSurvery.Surveryer/Views/Shared/SurveyResultOverview.cshtml
@model smsSurvey.dbInterface.SurveyTemplate

@{Html.RenderPartial("ReportFilterArea");}

<div class="clear:both"></div>
<fieldset class="overviewFieldSet">
    <legend> Overview: @Model.Description </legend>
   <img id="exportToExcel" title="Export raw data to Excel" class="exportData" src="/Content/images/Excel-25_chenar.png" width="25" height="25"/>
   <div class="graphsContainer" id="@String.Format("graphsOverviewContainer{0}", Model.Id)">
      <div id="@String.Format("tableOverviewChart_div{0}", Model.Id)"></div>
      <div id="@String.Format("pieOverviewChart_div{0}", Model.Id)"></div>

      <div id="@String.Format("loadingOverviewIndicator{0}", Model.Id)" style="display:none" class="loadingIndicatorArea">
         <div class="loadingIndicatorContainer">
            <img src="~/Content/images/ajax-loader_vs1.gif" class="loadingIndicatorIcon" />
         </div>
         <div class="overlay"></div>
      </div>
   </div>
    <div style="display: none" id="surveyId">@Model.Id</div>
</fieldset>

smsSurvery.Surveryer/Views/Shared/SurveyResultsDetails.cshtml
@model IEnumerable<smsSurvey.dbInterface.SurveyResult>

<h2>Survey results</h2>

<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateRan)
        </th>
        <th>
            Customer phone number
        </th>
        <th>
           Survey description
        </th>
       <th>
          @Html.DisplayNameFor(model => model.Terminated)
       </th>
       <th>
          I agree
       </th>
        <th>
          @Html.DisplayNameFor(model => model.PercentageComplete)
       </th>
        <th></th>
    </tr>
@foreach (var item in Model) 
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateRan)
        </td>
        <td>           
           @Html.ActionLink(item.Customer.PhoneNumber, "Details", "Customer", new { id = item.Customer.PhoneNumber }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SurveyTemplate.Description)
        </td>
       <td>
          @Html.DisplayFor(modelItem => item.Terminated)
       </td>
       <td>
          @Html.DisplayFor(modelItem => item.IAccept)
       </td>
       
       <td @( item.PercentageComplete == 1 ? "class=centopercent" : "")>       
          @Html.DisplayFor(modelItem => item.PercentageComplete)
       </td>
        <td>            
            @Html.ActionLink("Details", "Details", "SurveyResult", new { id=item.Id }, null) |
            @Html.ActionLink("Delete", "Delete", "SurveyResult", new { id=item.Id }, null)
        </td>
    </tr>
}
</table>

smsSurvery.Surveryer/Views/Shared/_Layout.cshtml
@using smsSurvery.Surveryer.Utilities
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8" />
   <title>@ViewBag.Title | Loyalty Insights</title>
   <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
   <meta name="viewport" content="width=device-width" />
   @Styles.Render("~/Content/css")
   @Scripts.Render("~/bundles/modernizr")
   
       @RenderSection("css", required: false)  
</head>
<body>
   <header>
      <div class="content-wrapper">
         <div class="float-left logo">            
            @Url.ImageLink(Url.Content("~/Content/images/logo.png"), "home", "Index", "SurveyTemplate", "Survey templates", null, "logo")
         </div>
         <div class="float-right">
            <section id="login">
               @Html.Partial("_LoginPartial")
            </section>
            @if (User.Identity.IsAuthenticated)
            {
               <nav>
                  <ul id="menu">
                     <li>@Html.ActionLink("Manual survey", "ManualSurvey", "Home")</li>

                     <li>@Html.ActionLink("Surveys", "Index", "SurveyTemplate")</li>
                     <li>@Html.ActionLink("Locations", "Index", "Locations")</li>
                     <li>@Html.ActionLink("Devices", "Index", "Devices")</li>
                     <li>@Html.ActionLink("Responses", "Index", "SurveyResult")</li>

                  </ul>
               </nav>  
            }
         </div>
      </div>
   </header>
   <div id="body">
      @RenderSection("featured", required: false)
      <section class="content-wrapper main-content clear-fix">
         @RenderBody()
      </section>
   </div>
   <footer>
      <div class="content-wrapper">
         <div class="float-left">
            <p>&copy; @DateTime.Now.Year - TxtFeedback</p>
         </div>
      </div>
   </footer>

   @Scripts.Render("~/bundles/jquery")
   @RenderSection("scripts", required: false)
</body>
</html>